### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 69Flick** [robert-axelrod/youtube-view-bot#3]
When i am launching the application it goes around 50% and this error pops up
![Screenshot 2023-11-22 160411](https://github.com/robert-axelrod/youtube-view-bot/assets/151796640/719caa9b-c9ac-40c8-abda-edb210d10f4f)

ERROR- Failed to Write Engine File
![Screenshot 2023-11-22 160411](https://github.com/robert-axelrod/youtube-view-bot/assets/151796640/e29a4b21-97e3-4655-9fd5-aea3c3ac0f50)

**Comment by robert-axelrod** [comment]
Try disabling all antiviruses, firewalls and enable VPN (in case your ISP can block connection to BAS servers). If all else fails, try to run the program on another PC or server.

**Comment by dotsk2** [comment]
Can I get the Credentials? Thanks
